import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>perplexity-clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-cols-[330px_1fr] bg-[#F3F3EE]">
        <aside className="flex flex-col">
          <div className="w-[330px] p-[30px] pr-[21px]">
            <div className="flex justify-between">
              <Image src="/logo/logo.svg" alt="" width={210} height={48} />
              <Image src="/icons/Collapse.svg" alt="" width={18} height={15} />
            </div>
            <div className="mt-[30px] flex items-center justify-between rounded-4xl bg-[#FCFCF9] p-[12px] pl-[24px] text-[21px] text-[#64645F]">
              New Thread
              <div className="flex gap-[1px]">
                <span className="rounded-[7px] border border-gray-300 px-[7px] text-[17px]">
                  Ctrl
                </span>
                <span className="rounded-[7px] border border-gray-300 px-[7px] text-[17px]">
                  ⇧
                </span>
                <span className="rounded-[7px] border border-gray-300 px-[7px] text-[17px]">
                  P
                </span>
              </div>
            </div>
            <menu className="mt-[42px] grid gap-[37px]">
              <li className="flex items-center gap-[12px] text-[23px] font-semibold text-[#13343B]">
                <Image
                  src="/icons/magnifying-glass.svg"
                  alt=""
                  width={23}
                  height={23}
                />
                Home
              </li>
              <li className="flex items-center gap-[12px] text-[23px] font-medium text-[#64645F]">
                <Image
                  src="/icons/discover.svg"
                  alt=""
                  width={23}
                  height={23}
                />
                Discover
              </li>
              <li className="flex items-center gap-[12px] text-[23px] font-medium text-[#64645F]">
                <Image src="/icons/Spaces.svg" alt="" width={23} height={23} />
                Spaces
              </li>
              <li className="flex items-center gap-[12px] text-[23px] font-medium text-[#64645F]">
                <Image src="/icons/Library.svg" alt="" width={23} height={23} />
                Library
              </li>
            </menu>
          </div>

          <div className="flex border-y-[1px] border-[#E6E6DE] p-[18px] justify-between">
            <span className="flex gap-[13px] items-center text-[20px] font-medium">
              <div className="h-[47px] w-[47px] rounded-full bg-[#E8E8E3]"></div>
              user
            </span>
            <span className="flex gap-[30px]">
              <Image src="/icons/arrow.svg" alt="" width={20} height={20} />
              <Image src="/icons/star.svg" alt="" width={21} height={21} />
            </span>
          </div>
        </aside>
        <div className="container m-3 ml-0 flex flex-col items-center justify-center gap-12 rounded-xl bg-[#FCFCF9] px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]"></h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
        </div>
      </main>
    </>
  );
}
