import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>perplexity-clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid min-h-screen grid-cols-[330px_1fr] bg-[#F3F3EE]">
        <aside className="w-[330px] p-[30px] pr-[21px]">
          <div className="flex justify-between">
            <Image src="/logo/logo.svg" alt="" width={210} height={48} />
            <Image src="/icons/Collapse.svg" alt="" width={18} height={15} />
          </div>
          <div className="mt-[30px] flex items-center justify-between rounded-4xl bg-[#FCFCF9] text-[#64645F] p-[12px] pl-[24px] text-[21px]">
            New Thread
            <div className="flex gap-[1px]"> 
              <span className="rounded-[7px] border border-gray-300 px-[7px] text-[17px]">
                Ctrl
              </span>
              <span className="rounded-[7px] border border-gray-300 px-[7px] text-[17px]">
                ⇧
              </span>
              <span className="rounded-[7px] border border-gray-300 px-[7px] text-[17px]">
                P
              </span>
            </div>
          </div>
        </aside>
        <div className="container m-3 ml-0 flex flex-col items-center justify-center gap-12 rounded-xl bg-[#FCFCF9] px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]"></h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
        </div>
      </main>
    </>
  );
}
